dist: trusty
language: ruby

rvm:
  - 2.4

install:
  - gem install jekyll
  - gem install jekyll-paginate
  - gem install html-proofer
  - gem install jekyll-gist
  - gem install jekyll-sitemap
  - git clone https://github.com/neomutt/neomutt.github.io

branches:
  only:
    - devel/fix-issue-19
script:
  - cd neomutt.github.io && jekyll build && htmlproofer ./_site
