dist: trusty
language: ruby

git:
  depth: 1


cache:
  bundler: true
  directories:
  - $HOME/.cache/.htmlproofer

install:
  - git clone https://github.com/neomutt/neomutt.github.io
  - gem install jekyll
  - gem install jekyll-gist
  - gem install jekyll-sitemap
  - gem install jekyll-mentions
  - gem install html-proofer
  - gem install algoliasearch-jekyll

script:
    - rake

