notifications:
  email:
    recipients:
      - toogley@mailbox.org
    on_success: change
    on_failure: always

dist: trusty
language: ruby

rvm:
  - 2.4

install:
  - gem install jekyll
  - gem install html-proofer
  - git clone https://github.com/neomutt/neomutt.github.io

script:
  - jekyll build && htmlproofer ./_site
